services:
  bulk-recruiter:
    image: 280710007209.dkr.ecr.ap-south-2.amazonaws.com/cold-email-python:latest
    container_name: bulk-recruiter
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
